version: "3"
services:
  bot:
    build: .
    environment:
      LISTENER_BOT_ID: $LISTENER_BOT_ID
      SPEAKER_BOT_ID: $SPEAKER_BOT_ID
    volumes:
      - ./:/src/ukeuri
    working_dir: /src/ukeuri
    command: "go run main.go"
